version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      target: ${ENVIRONMENT:-production-pseudo}
    networks:
      - default
    volumes:
      - .:/web/xxx-blog

  alb:
    build:
      context: docker/alb
      target: development
    ports:
      - ${ALB_PORT:-443}:443

networks:
  default:
    name: xxx-blog_default
    driver: bridge