version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      target: ${ENVIRONMENT:-production-pseudo}
    networks:
      - default
    volumes:
      - .:/web/xxx-blog

  alb:
    build:
      context: docker/alb
      target: development
    ports:
      - ${ALB_PORT:-443}:443

  mysql:
    build:
      context: docker/mysql
      target: development
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: xxx-blog
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql

networks:
  default:
    name: xxx-blog_default
    driver: bridge

volumes:
  mysql: