version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
      target: ${ENVIRONMENT:-production-pseudo}

  alb:
    build:
      context: docker/alb
      target: development
    ports:
      - ${ALB_PORT:-443}:443
