version: "3.7"
services:
  node:
    build:
      context: .
      target: ${ENVIRONMENT:-production-pseudo}
    networks:
      - default
    ports:
      - ${WEBPACK_PORT:-8080}:8080
    volumes:
      - .:/web/xxx-blog/front

networks:
  default:
    name: xxx-blog_default
    driver: bridge