#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_users:
  path: /users
  controller: App\Controller\UsersController::index
  methods: GET|HEAD

app_user_create:
  path: /user/create
  controller: App\Controller\User\CreateController::index
  methods: POST