version: "3.7"
services:
  php-fpm:
    build:
      context: .
      target: ${ENVIRONMENT:-production-pseudo}
      # labels:
      #   com.docker.compose.project: ${PROJECT_NAME}
      #   com.docker.compose.service: php-fpm
    networks:
      - default
    volumes:
      - .:/web/xxx-blog/api

networks:
  default:
    name: xxx-blog_default
    driver: bridge